import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MD Banana Stand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/thw0szv.css" />
      </head>
      <body className={`${inter.className} bg-[#184623] text-white`}>
        <Header />
        {children}
        <img
          src="/footer.png"
          alt="footer graphic"
          className="w-full h-[240px] object-cover bg-inherit -mb-[241px] hidden md:block"
        />
        <Footer />
      </body>
    </html>
  );
}
